cal_exersize/app.py
from flask import Flask, render_template, Response, blueprints
import cv2
import mediapipe as mp
from cal_exersize.exercise.service import Exersize_service
from routes.exec_route import bp as exec_bp


app = Flask(__name__)
app.register_blueprint(exec_bp)

@app.route('/')
def hello():
    return render_template('index.html')


if __name__ == '__main__':
    app.run(debug=True)

cal_exersize/routes/exec_route.py
from flask import Flask, Blueprint, Response, render_template, request, session
from cal_exersize.exercise.service import Exersize_service

exec = Exersize_service()


bp = Blueprint('exec', __name__, url_prefix='/exec')

@bp.route('/select_exec')
def select_exec():
    return render_template('select_exec.html')


# @bp.route('/run_exec/<string:exec_name>')
# def run_exec(exercise_index):
#     exec_name = exec.getExecName(exercise_name)
#     return render_template('run_exec.html', exec_name=exec_name)


@bp.route('/exec_result')
def exec_result():
    counter = exec.counter
    calories = exec.calories
    return render_template('exec_result.html', counter=counter, calories=calories)


@bp.route('/video_feed_arm_curl')
def video_feed_arm_curl():
    return Response(exec.arm_curl(), mimetype='multipart/x-mixed-replace; boundary=frame')

@bp.route('/video_feed_chair_dips')
def video_feed_chair_dips():
    return Response(exec.chair_dips(), mimetype='multipart/x-mixed-replace; boundary=frame')

@bp.route('/video_feed_crunch')
def video_feed_crunch():
    return Response(exec.crunch(), mimetype='multipart/x-mixed-replace; boundary=frame')

@bp.route('/video_feed_leg_raise')
def video_feed_leg_raise():
    return Response(exec.leg_raise(), mimetype='multipart/x-mixed-replace; boundary=frame')

@bp.route('/video_feed_lunge')
def video_feed_lunge():
    return Response(exec.lunge(), mimetype='multipart/x-mixed-replace; boundary=frame')

@bp.route('/video_feed_pull_up')
def video_feed_pull_up():
    return Response(exec.pull_up(), mimetype='multipart/x-mixed-replace; boundary=frame')

@bp.route('/video_feed_push_up')
def video_feed_push_up():
    return Response(exec.push_up(), mimetype='multipart/x-mixed-replace; boundary=frame')

@bp.route('/video_feed_side_lateral_raise')
def video_feed_side_lateral_raise():
    return Response(exec.side_lateral_raise(), mimetype='multipart/x-mixed-replace; boundary=frame')

@bp.route('/video_feed_squat')
def video_feed_squat():
    return Response(exec.squat(), mimetype='multipart/x-mixed-replace; boundary=frame')

cal_exersize/templates/exec_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
운동 종료!!
<br>
총 운동 횟수: {{counter}}
<br>
총 소모한 칼로리: {{calories}}
</body>
</html>

cal_exersize/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<a href="/exec/select_exec">운동하러 가자!!!</a>
</body>
</html>

cal_exersize/templates/run_exec.html
<!DOCTYPE html>
<html>
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-8  offset-lg-2">
            <h3 class="mt-5">운동하기!!</h3>
            {%if index == 1%}
            <img src="{{ url_for('exec.video_feed_push_up') }}" width="80%">
            {%elif index == 2%}
            <img src="{{ url_for('exec.video_feed_squat') }}" width="80%">
            {%elif index == 3%}
            <img src="{{ url_for('exec.video_feed_crunch') }}" width="80%">
            {%elif index == 4%}
            <img src="{{ url_for('exec.video_feed_leg_raise') }}" width="80%">
            {%elif index == 5%}
            <img src="{{ url_for('exec.video_feed_dips') }}" width="80%">
            {%elif index == 6%}
            <img src="{{ url_for('exec.video_feed_arm_curl') }}" width="80%">
            {%elif index == 7%}
            <img src="{{ url_for('exec.video_feed_lunge') }}" width="80%">
            {%elif index == 8%}
            <img src="{{ url_for('exec.video_feed_pull_up') }}" width="80%">
            {%elif index == 9%}
            <img src="{{ url_for('exec.video_feed_side_lateral_raise') }}" width="80%">
            {%endif%}
            <form action="/exec/exec_result">
                <input type="submit" name="end_exec" value="운동종료">
            </form>
        </div>
    </div>
</div>
</body>


</html>

cal_exersize/templates/select_exec.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>운동선택페이지</title>
</head>
<body>
<h1>하고 싶은 운동을 선택해주세요!</h1>

<form action="/exec/run_exec/{{}}">
    <input type="submit" name="Arm_curl" value="Arm_curl">
</form>
<form action="/exec/run_exec/{{Chair_dips}}">
    <input type="submit" name="Chair_dips" value="Chair_dips">
</form>
<form action="/exec/run_exec/{{Crunch}}">
    <input type="submit" name="Crunch" value="Crunch">
</form>
<br>
<form action="/exec/run_exec/{{Leg_raise}}">
    <input type="submit" name="Leg_raise" value="Leg_raise">
</form>
<form action="/exec/run_exec/{{Lunge}}">
    <input type="submit" name="Lunge" value="Lunge">
</form>
<form action="/exec/run_exec/{{Pull_up}}">
    <input type="submit" name="Pull_up" value="Pull_up">
</form>
<br>
<form action="/exec/run_exec/{{Push_up}}">
    <input type="submit" name="Push_up" value="Push_up">
</form>
<form action="/exec/run_exec/{{Side_lateral_raise}}">
    <input type="submit" name="Side_lateral_raise" value="Side_lateral_raise">
</form>
<form action="/exec/run_exec/{{Squat}}">
    <input type="submit" name="Squat" value="Squat">
</form>

</body>
</html>